---
- name: Getting authorized_key
  hosts: all
  gather_facts: False


  tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user: "{{ key_user }}"
        state: present
        key: "{{lookup('file', '/home/sshkey/redpub')}}"
