---
- name: Makeing Changes to Authorized key
  hosts: all
  gather_facts: False


  tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user: "{{ key_user}}"
        state: "{{ state }}"
        key: "{{ authorized_key }}"
