---
- name: Makeing Changes to Authorized key
  hosts: all
  gather_facts: False


  tasks:
    - name: Authorized key set to {{ state }} from Survey for {{ user }}
      authorized_key:
        user: "{{ key_user}}"
        state: "{{ state }}"
        key: "{{ authorized_key }}"
