---
- name: Check file diff
  hosts: all
  gather_facts: False


  tasks:
    - name: Grab Repo with source file
      git:
        repo: "{{ sourcefilerepo }}"
        dest: /tmp/demo
        accept_hostkey: yes
        force: yes
      delegate_to: 127.0.0.1
      run_once: true

    - name: Check for variance in File and make changes if needed
      copy:
        src: "/tmp/demo/{{ file2comp }}"
        dest: "/etc/{{ file2comp }}"
      diff: yes
      register : filechanges

    - name: stat check_mode
      stat:
        path: "/etc/{{ file2comp }}"
      when: filechanges.changed == true
      register: statvar
