---
- name: Create the Ansible service account on target hosts
  hosts: all
  gather_facts: True
  tasks:
    - name: service account is present
      user:
        name: "{{ svcansible_username }}"
        home: "{{ svcansible_home }}/{{ svcansible_username }}"
        comment: Service account for Ansible
        state: present
        system: True

    - name: The public key for the service account is present
      authorized_key:
        user: "{{ svcansible_username }}"
        state: present
        key: "{{ svcansible_public_key }}"

    - name: svcansible is included in sudoers.d
      copy:
        dest: "/etc/sudoers.d/{{ svcansible_username }}"
        content: "{{ svcansible_username }} ALL=(ALL) NOPASSWD: ALL\n"
        owner: root
        group: root
        mode: 'ug+rwX,o='
      when: svcansible_sudoer == 'true'
