---
- name: Assigning Insight Role to Servers
  hosts: all
  tasks:
    - include_role:
        name: RedHatInsights.insights-client
      tags: ['insights']
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version > "5"
