---
- name: Set Default Repos for RHEL 7
  hosts: all
  gather_facts: True
  vars:

  tasks:
    - name: Rhel 7 specific Repos
      block:
        - name: Disable all Repos
          rhsm_repository:
            name: '*'
            state: disabled
        - name: Enable rhel-7-server-rpms
          rhsm_repository:
            name: rhel-7-server-rpms
            state: enabled
        - name: Enable rhel-7-server-extras-rpms
          rhsm_repository:
            name: rhel-7-server-extras-rpms
            state: enabled
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "7"
