---
- name: Stoping HTTPD service
  hosts: all
  gather_facts: False


  tasks:
  - name: Stop service httpd to cause Dyantrace problem
    ansible.builtin.service:
      name: httpd
      state: stopped
