---
- name: Remove requested package
  hosts: all
  gather_facts: False
  vars:
      package: ''
  serial: 1
  tasks:
    - name: Removing {{package}}
      yum:
        name: "{{package}}"
        state: absent
